### ISSUE TITLE
Where is github pages ?

### ISSUE THREAD

**Issue by ans-4175** [Imballinst/gulp-practice#1]
`http://imballinst.github.io/gulp-practice/` is it correct address for this github pages repo ?

**Comment by Imballinst** [comment]
Sorry, I had some trouble with the branches. It is up now, but I'm not sure why the page won't load any CSS/JS. Currently working at it.

**Comment by imballinst** [comment]
It is working now. I mixed up the master and gh-pages branch, hence so that happened. On the other note, I also fixed the problem where the page can't load "file.json", which was caused by the load.js. I changed it (line 1) from:

$.getJSON("../../file.json", function(json) { to
$.getJSON("file.json", function(json) {

If there is another issue, please notify me and I will work on it.
